---
- hosts: all
  gather_facts: false
  become: yes
  tasks:
    - name: "Get current hostname"
      shell: |
        cat /etc/hostname
      register: current_hostname

    - name: "Print the file content to a console"
      debug:
        msg: "{{ current_hostname.stdout }}"

    - name: "Replace line in file examples"
      become: yes
      become_user: root
      replace: 
        path: /etc/hostname
        regexp: '{{ current_hostname.stdout }}'
        replace: '{{ newhostname }}'
        backup: yes

    - name: "Replace line in file examples"
      become: yes
      become_user: root
      replace: 
        path: /etc/hosts
        regexp: '{{ current_hostname.stdout }}'
        replace: '{{ newhostname }}'
        backup: yes

    - name: reboot host
      reboot: