---
  - name: Start portainer stack
    hosts: all
    gather_facts: false
    tasks:
    - name: starting stack script
      script:
        executable: python3
        cmd: /home/will/custom_scripts/download-stack-start.py
    - name: Add login file
      command: sudo touch /home/will/Films/ha/login/login.txt
    - name: Pause for 10 minutes
      ansible.builtin.pause:
        minutes: 10
    - name: remove login file
      command: sudo rm /home/will/Films/ha/login/login.txt
    - name: starting stack script
      script:
        executable: python3
        cmd: /home/will/custom_scripts/download-stack-start.py