---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
  - name: Add nas to box
    ansible.builtin.lineinfile:
      path: /etc/fstab
      line: "{{ nas_share }}  /home/will/Films  nfs      defaults    0       0"
  - name: Mount nas
    command: sudo mount -a