---
- hosts: all
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - name: Unconditionally shut down the machine with all defaults
      community.general.shutdown:
    # - name: shutting down machine
    #   command: shutdown now