---
- hosts: all
  gather_facts: false
  become: yes

  tasks:
    - name: "Replace line in file examples"
      become: yes
      become_user: root
      replace: 
        path: /etc/cloud/cloud.cfg
        regexp: 'preserve_hostname: false'
        replace: 'preserve_hostname: true'
        backup: yes
        