---
- hosts: all
  gather_facts: false
  become: true
  become_user: root
  tasks:
    - name: Shutdown force
      command: ansible-playbook /etc/ansible/windows-ansible/shutdown-win.yaml -i /etc/ansible/hosts.ini