---
- hosts: all
  gather_facts: false
  become: true
  become_user: root
  tasks:
    - name: Spin up Linux VM
      command: ansible-playbook /etc/ansible/proxmox.yaml -i /etc/ansible/proxmoxhosts.ini  -e "@/etc/ansible/proxmoxvars.yml"