---
- hosts: all
  gather_facts: true
  # become: true
  # become_user: root
  # vars:
  #     ansible_shell_type: powershell
  #     ansible_shell_executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
  tasks:
    - name: create winlogin file
      win_command: cmd /k nul > C:\temp\login.txt
      # win_file:
      #   path: C:\temp\login.txt
      #   state: touch

  # - name: add login file
  #   command: sudo touch /home/will/Films/ha/login/login.txt
  # - name: Pause for 5 minutes to build app cache
  #   ansible.builtin.pause:
  #     minutes: 5
  # - name: remove login file.
  #   command: sudo rm /home/will/Films/ha/login/login.txt

    # - name: Set service startup mode to auto and ensure it is started
    #   ansible.windows.win_service:
    #     name: ssh-agent
    #     # start_mode: auto
    #     state: started
    # - name: Set service startup mode to auto and ensure it is started
    #   ansible.windows.win_service:
    #     name: sshd
    #     # start_mode: auto
    #     state: started
    # - name: Configure autologon
    #   win_command: "C:\\Program Files\\Autologon.exe {{ username }} {{ domain }} {{ password }}"
    # - name: Set service startup mode to auto and ensure it is started
    #   ansible.windows.win_service:
    #     name: ssh-agent
    #     # start_mode: auto
    #     state: stopped
    # - name: Set service startup mode to auto and ensure it is started
    #   ansible.windows.win_service:
    #     name: sshd
    #     # start_mode: auto
    #     state: stopped
      